name: flutter_application
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  
  # Serial Communication
  usb_serial: ^0.5.2
  libserialport: ^0.3.0+1
  
  # State Management
  provider: ^6.1.1
  
  # UI Enhancements
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0
  
  # Utilities
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
